version: "3"
services:
  # postgres:
  #   image: "postgres:latest"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
    # volumes:
    #   - ./client:/etc/nginx/html
  # nginx:
  #   depends_on:
  #       - client
    #   - api
    # restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./nginx
  # api:
  #   depends_on:
  #     - postgres
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./server"
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   environment:
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
